server:
  ssl:
    key-alias: northstar
    key-store-type: PKCS12
    key-store: classpath:keystore/northstarKeyStore.p12
    key-store-password: northstar666
northstar: 
  socketio: 51688
  data-service:
    baseUrl: https://service.quantit.tech:44388
    
logging:
  level: 
    root: info
  file:
    path: logs/
  
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/storage;DB_CLOSE_ON_EXIT=FALSE;
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: ${env:dev}
  threads:
    virtual:
      enabled: true
---
server:
  port: 443
  ssl:
    enabled: true
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
spring:
  config:
    activate:
      on-profile: prod
      
---
server:
  port: 80
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 80
  ssl:
    enabled: false
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  config:
    activate:
      on-profile: test,unittest,train
      
---
server:
  port: 443
  ssl:
    enabled: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  config:
    activate:
      on-profile: e2e

